	;OMAR ALEXIS CHI CANCHE
	;POOL DIAZ ANGEL ENRIQUE
;SEXTO SEMESTRE GRUPO B 
;LENGUAJES Y AUTOMATAS 2
	;JOSE LEONEL PECH MAY
;SISTEMAS COMPUTACIONALES
;TECNM VALLADOLID

DATO1MENU MACRO STRING
    mov ax,@data    
    mov ds,ax        
ENDM

DATO2MENU MACRO STRING
    mov ax,@data     
    mov ds,ax       
ENDM

INIABC MACRO    ;INICIO DE MACRO DE ABECEDARIO
    MOV BL,90   ;MUEVO EL CONTENIDO DE 90 A BL
    MOV CL,26   ;MUEVO EL NUMERO 26 QUE CORRESPONDE AL TOTAL DE LAS LETRAS PARA HACER EL DECREMENTO
ENDM            ;FINALIZA MACRO DE INIABC

FINPROG MACRO   ;INICIO DE MACRO DE FINPROG PARA FINALIZAR PROGRAMA
    MOV AH,4CH
    INT 21H
ENDM

LIMPIAR MACRO
    mov ax,0600h;RECORRIDO DE PANTALLA
    mov bh,07h  ;APLICAMOS FONDO NEGRO 0 Y LETRAS LIGHT GRAY 7
    mov cx,0000h;ESQUINA SUPERIOR IZQUIERDA RENGLON
    mov dx,184Fh;ESQUINA INFERIOR DERECJ¿HA RENGLON
    int 10h     ;INTERRUPCION DEL BIOS LLAMADA
ENDM


.MODEL SMALL
ORG 100H

INCLUDE 'emu8086.inc' ;INCLUYE FUNCIONES DE LA LIBRERIA EMU8086.INC
DEFINE_SCAN_NUM       ; PARA LEER NUMEROS
DEFINE_PRINT_STRING   ; PARA VALORES DE TIPO STRING
DEFINE_PRINT_NUM
DEFINE_PRINT_NUM_UNS
 
.STACK 100H           ; RESERVAMOS LA PILA EN TAMANO 100
.DATA
MENU db 13,10,"--------MENU PRINCIPAL----------",13,10  
     db "Selecciona una opcion:",13,10
     db "1. OPERACIONES",13,10
     db "2. SALIR",13,10, '$'; DECLARAMOS EL MENU
MENU1 db '1 OPERACIONES',13,10,'$'    
MENU2 db '2 SAlIR',13,10,'$'; DECLARAMOS VARIABLES DEL MENU

SUBMENU db 13,10,"--------MENU OPERACIONES----------",13,10 
     db "Selecciona una opcion:",13,10  
     db "1. SUMA",13,10
     db "2. RESTA",13,10
     db "3. MULTIPLICACION",13,10
     db "4. DIVISION",13,10
     db "5. SALIR AL MENU PRINCIPAL",13,10, '$' ; DECLARAMOS EL SUBMENU
MENU4 db '1 SUMA',13,10,'$'
MENU5 db '2 RESTA',13,10,'$'; DECLARAMOS VARIABLES DEL MENU
MENU6 db '3 MULTIPLICACION',13,10,'$'; DECLARAMOS VARIABLES DEL MENU
MENU7 db '4 DIVISION',13,10,'$'; DECLARAMOS VARIABLES DEL MENU
     
VALOR1 db 13,10,13,10,'DIGITE EL PRIMER NUMERO Y PRESIONE ENTER : $' ;VARIABLES PARA GUARDAR LOS DIVERSOS MENSAJES A IMPRIMIR
VALOR2 db 13,10,13,10,'DIGITE EL SEGUNDO NUMERO Y PRESIONE ENTER : $'
VALOR3 db 13,10,13,10, 'LA SUMA ES : $'
VALOR4 db 13,10,'LA RESTA ES : $'
VALOR5 db 13,10,'LA MULTIPLICACION ES : $'
VALOR6 db 13,10,'LA DIVISION ES : $' 
DIGITO1 dw ? ;DEFINIMOS VARIABLES DE DOS BYTES SIN NINGUN VALOR
DIGITO2 dw ? ;DEFINIMOS VARIABLES DE DOS BYTES SIN NINGUN VALOR
RESIDUO db 13,10,13,10, 'EL RESIDUO ES : $'

.CODE

    INICIO:
    
         MOV AX,@DATA     ;LLAMAMOS AL DATA
         MOV DS, AX       ;GUARDAMOS LOS DATOS DS
         
         LEA DX,MENU      ;IMPRIMIMOS EL MENSAJE QUE CONTIENE MENU 
         MOV AH,9H
         INT 21H         ;INTERRUPCION DE DOS
         MOV AH,08        ;PAUSA PARA ESPERAR QUE USUARIO PRESIONE UNA TECLA
         INT 21H          ;INTERRUPCION DE DOS
         CMP AL,49        ;COMPARAMOS LO INGRESADO CON EL VALOR DE 1 EN HEX ES 49
         JE llamarOperaciones; EN CASO DE SER IGUAL LLAMAMOS A LA FUNCION    
         CMP AL,50        ;COMPARAMOS LO INGRESADO CON EL VALOR DE 2 EN HEX ES 50
         JE llamarSalir   ; EN CASO DE SER IGUAL LLAMAMOS A LA FUNCION

    
    FINPROG; MACRO PARA FINALIZAR EL PROGRAMA


llamarOperaciones:
 CALL Operaciones   ;LLAMAMOS AL PROCEDIMIENTO

llamarSalir:
 CALL Salir         ;LLAMAMOS AL PROCEDIMIENTO

                    
Operaciones:
    LEA DX,MENU1         ;LEEMOS EL MENSAJE QUE CONTIENE MENU1
    MOV AH,9H            ;IMPRESION DE PANTALLA DEL MENSAJE
    INT 21H 
        INISUBMENU:
 
         MOV AX,@DATA    ;LLAMAMOS AL DATA
         MOV DS, AX      ;GUARDAMOS LOS DATOS DS
         
         LEA DX,SUBMENU  ;IMPRIMIMOS EL MENSAJE QUE CONTIENE MENU 
         MOV AH,9H       ;IMPRESION DE PANTALLA DEL MENSAJE
         INT 21H         ;INTERRUPCION DE DOS
         
         MOV AH,08       ;PAUSA PARA ESPERAR QUE USUARIO PRESIONE UNA TECLA
         INT 21H         ;INTERRUPCION DE DOS
         
         CMP AL,49       ;COMPARAMOS LO INGRESADO CON EL VALOR DE 1 EN HEX ES 49
         JE llamarSuma; EN CASO DE SER IGUAL LLAMAMOS A LA FUNCION    
         CMP AL,50        ;COMPARAMOS LO INGRESADO CON EL VALOR DE 2 EN HEX ES 50
         JE llamarResta   ; EN CASO DE SER IGUAL LLAMAMOS A LA FUNCION
         CMP AL,51        ;COMPARAMOS LO INGRESADO CON EL VALOR DE 2 EN HEX ES 50
         JE llamarMultiplicacion   ; EN CASO DE SER IGUAL LLAMAMOS A LA FUNCION
         CMP AL,52        ;COMPARAMOS LO INGRESADO CON EL VALOR DE 2 EN HEX ES 50
         JE llamarDivision   ; EN CASO DE SER IGUAL LLAMAMOS A LA FUNCION
         CMP AL,53      ;COMPARAMOS LO INGRESADO CON EL VALOR DE 4 EN HEX ES 52
         JE llamarSalir2           ; EN CASO DE SER IGUAL LLAMAMOS A LA FUNCION

llamarSuma:
 CALL Suma          ;LLAMAMOS AL PROCEDIMIENTO
 
llamarResta:
 CALL Resta         ;LLAMAMOS AL PROCEDIMIENTO

llamarMultiplicacion:
 CALL Multiplicacion;LLAMAMOS AL PROCEDIMIENT0

llamarDivision:
 CALL Division      ;LLAMAMOS AL PROCEDIMIENTO

llamarSalir2:       ;LLAMAMOS AL PROCEDIMIENTO
 CALL Salir2
;**************************************************************
 Suma PROC NEAR         ;INICIAMOS LA FUNCION
        LEA DX,MENU4    ;LEEMOS EL MENSAJE QUE CONTIENE MENU4 
        MOV AH,09       ;IMPRESION DE PANTALLA DEL MENSAJE
        INT 21H;INTERRUPCION DE DOS
        MOV AH,09 ;instruccion para imprimir en pantalla
        LEA DX,VALOR1 ;LEEMOS EL MENSAJE QUE CONTIENE VALOR1 
        INT 21H;INTERRUPCION DE DOS
            
        CALL SCAN_NUM ;LLAMA A LA FUNCION SCAN_NUM PARA EL VALOR DEL TECLADO 
        MOV DIGITO1, CX ;MUEVE EL NUMERO AL DIGITO1 
                      
        MOV AH,09     ;IMPRESION DE PANTALLA DEL MENSAJE
        LEA DX,VALOR2 ;LEEMOS EL MENSAJE QUE CONTIENE VALOR2
        INT 21H ;INTERRUPCION DE DOS
             
        CALL SCAN_NUM ;LLAMAMOS AL VALOR QUE SE HA INGRESADO 
        MOV DIGITO2,CX ;MOVEMOS A CX A DIGITO2 
               
        MOV AH,09      ;IMPRESION DE PANTALLA DEL MENSAJE
        LEA DX,VALOR3  ;LEEMOS EL MENSAJE QUE CONTIENE VALOR3
        INT 21H ;INTERRUPCION DE DOS
             
        MOV AX,DIGITO1;MUEVE EL NUMERO A AX
        ADD AX,DIGITO2;LE SUMA EL VALOR QUE CONTIENE AX 
        CALL PRINT_NUM 
 CALL INISUBMENU    ;REGRESAMOS AL CICLO INISUBMENU
 RET
 Suma ENDP          ;FINALIZA LA FUNCION
 ;*************************************************************
Resta PROC NEAR         ;INICIAMOS LA FUNCION
        LEA DX,MENU5    ;LEEMOS EL MENSAJE QUE CONTIENE MENU5 
        MOV AH,09       ;IMPRESION DE PANTALLA DEL MENSAJE
        INT 21H;INTERRUPCION DE DOS
        MOV AH,09 ;instruccion para imprimir en pantalla
        LEA DX,VALOR1 ;LEEMOS EL MENSAJE QUE CONTIENE VALOR1 
        INT 21H;INTERRUPCION DE DOS
            
        CALL SCAN_NUM ;LLAMA A LA FUNCION SCAN_NUM PARA EL VALOR DEL TECLADO 
        MOV DIGITO1, CX ;MUEVE EL NUMERO AL DIGITO1 
                      
        MOV AH,09     ;IMPRESION DE PANTALLA DEL MENSAJE
        LEA DX,VALOR2 ;LEEMOS EL MENSAJE QUE CONTIENE VALOR2
        INT 21H ;INTERRUPCION DE DOS
             
        CALL SCAN_NUM ;LLAMAMOS AL VALOR QUE SE HA INGRESADO 
        MOV DIGITO2,CX ;MOVEMOS A CX A DIGITO2 
               
        MOV AH,09      ;IMPRESION DE PANTALLA DEL MENSAJE
        LEA DX,VALOR4  ;LEEMOS EL MENSAJE QUE CONTIENE VALOR4
        INT 21H ;INTERRUPCION DE DOS
             
        MOV AX,DIGITO1;MUEVE EL NUMERO A AX
        SUB AX,DIGITO2;LE SUMA EL VALOR QUE CONTIENE AX 
        CALL PRINT_NUM 
 CALL INISUBMENU    ;REGRESAMOS AL CICLO INISUBMENU
 RET
 Resta ENDP          ;FINALIZA LA FUNCION
;************************************************************
 Multiplicacion PROC NEAR ;INICIAMOS LA FUNCION
        LEA DX,MENU6    ;LEEMOS EL MENSAJE QUE CONTIENE MENU6 
        MOV AH,09       ;IMPRESION DE PANTALLA DEL MENSAJE
        INT 21H;INTERRUPCION DE DOS
        MOV AH,09 ;IMPRESION DE PANTALLA DEL MENSAJE
        LEA DX,VALOR1 ;LEEMOS EL MENSAJE QUE CONTIENE VALOR1 
        INT 21H;INTERRUPCION DE DOS
            
        CALL SCAN_NUM ;LLAMA A LA FUNCION SCAN_NUM PARA EL VALOR DEL TECLADO 
        MOV DIGITO1, CX ;MUEVE EL NUMERO AL DIGITO1 
                      
        MOV AH,09     ;IMPRESION DE PANTALLA DEL MENSAJE
        LEA DX,VALOR2 ;LEEMOS EL MENSAJE QUE CONTIENE VALOR2
        INT 21H ;INTERRUPCION DE DOS
             
        CALL SCAN_NUM ;LLAMAMOS AL VALOR QUE SE HA INGRESADO 
        MOV DIGITO2,CX ;MOVEMOS A CX A DIGITO2 
               
        MOV AH,09      ;IMPRESION DE PANTALLA DEL MENSAJE
        LEA DX,VALOR5  ;LEEMOS EL MENSAJE QUE CONTIENE VALOR5
        INT 21H ;INTERRUPCION DE DOS
        MOV AX,DIGITO1 ;MUEVE EL DIGITO1 A AX 
        MOV BX,DIGITO2 ;MUEVE EL DIGITO2  A BX
        MUL BX ; REALIZAMOS LA MUTIPLICACION
        CALL PRINT_NUM  ; LLAMAMOS A LA FUNCION PRINT_NUM
        CMP BL,0    ; COMPARAMOS 0 CON BL 
 CALL INISUBMENU
 RET
 Multiplicacion ENDP  ;FINALIZA LA FUNCION MULTIPLICACION
 ;*************************************************************
 Division PROC NEAR         ;INICIAMOS LA FUNCION
        LEA DX,MENU7    ;LEEMOS EL MENSAJE QUE CONTIENE MENU7 
        MOV AH,09       ;IMPRESION DE PANTALLA DEL MENSAJE
        INT 21H;INTERRUPCION DE DOS
        MOV AH,09 ;instruccion para imprimir en pantalla
        LEA DX,VALOR1 ;LEEMOS EL MENSAJE QUE CONTIENE VALOR1 
        INT 21H;INTERRUPCION DE DOS
            
        CALL SCAN_NUM ;LLAMA A LA FUNCION SCAN_NUM PARA EL VALOR DEL TECLADO 
        MOV DIGITO1, CX ;MUEVE EL NUMERO AL DIGITO1 
                      
        MOV AH,09     ;IMPRESION DE PANTALLA DEL MENSAJE
        LEA DX,VALOR2 ;LEEMOS EL MENSAJE QUE CONTIENE VALOR2
        INT 21H ;INTERRUPCION DE DOS
             
        CALL SCAN_NUM ;LLAMAMOS AL VALOR QUE SE HA INGRESADO 
        MOV DIGITO2,CX ;MOVEMOS A CX A DIGITO2 
               
        MOV AH,09      ;IMPRESION DE PANTALLA DEL MENSAJE
        LEA DX,VALOR6  ;LEEMOS EL MENSAJE QUE CONTIENE VALOR6
        INT 21H ;INTERRUPCION DE DOS
         
        XOR DX,DX ;DEJA EN CERO DX, PARA QUE NO SE DESBORDE LA DIVISION
        ;DX ALMACENA EL MODULO DE LA DIVISION, POR ESO HAY Q DEJARLO EN CERO
        MOV AX,DIGITO1 ;MUEVE PRIMER NUMERO DIGITADO A AX
        MOV BX,DIGITO2 ;MUEVE SEGUNDO NUMERO DIGITADO A BX
        DIV BX ;AX = AX/BX
        CALL PRINT_NUM
        
 CALL INISUBMENU    ;REGRESAMOS AL CICLO INISUBMENU
 RET
 Division ENDP          ;FINALIZA LA FUNCION
 ;********************************************************* 
 Salir2 PROC NEAR
 LIMPIAR            ;LIMPIAMOS PANTALLA AL SALIR DEL SEGUNDO MENU

 CALL INICIO        ;REGRESAMOS AL CICLO INICIO
 RET
 Salir2 ENDP        ; SALIMOS DE LA FUNCION SALIR2
;*************************************************************** 
SALIR PROC NEAR
    MOV AX,4C00H       ;FINALIZA EL PROGRAMA
    INT 21H 
SALIR ENDP

END INICIO              ;FIN DE INICIO
FINPROG  